echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async
echo -n "" | faas-cli invoke memory-function --async

